find / -name "*libbluetoth*" -print -delete
find / -name "*girepository*" -print -delete
find / -name "*aspell*" -print -delete
find / -name "*libbrotli*" -print -delete
find / -name "*libdb*" -print -delete
find / -name "*libedataserver*" -print -delete
find / -name "*libfdisk*" -print -delete
find / -name "*libgdk*" -print -delete
find / -name "*libgnome*" -print -delete
find / -name "*libldb*" -print -delete
