rm -rfv ./.cache
rm -rfv ./.mozilla
rm -rfv /var/cache/*
rm -rfv /etc/firewalld/
rm -rfv /etc/services
rm -rfv /etc/udev
rm -rfv /home/peterk/.cache/*
rm -rfv /home/peterk/.local/
rm -rfv /home/peterk/.mozilla
rm -rfv /home/peterk/Downloads/
rm -rfv /home/peterk/master.zip
rm -rfv /home/peterk/otter-browser-master/
rm -rfv /home/peterk/rpmbuild/sources
rm -rfv /home/rpmbuild/sources
rm -rfv /lib/modules
rm -rfv /lib64/bluetooth
rm -rfv /lib64/dri/i965_dri.so
rm -rfv /lib64/dri/nouveau_dri.so
rm -rfv /lib64/dri/r600_dri.so
rm -rfv /lib64/dri/radeonsi_dri.so
rm -rfv /lib64/dri/virtio_gpu_dri.so
rm -rfv /lib64/dri/vmwgfx_dri.so
rm -rfv /lib64/games
rm -rfv /root/.cache
rm -rfv /root/.mozilla
rm -rfv /root/Downloads
rm -rfv /root/mozilla
rm -rfv /root/rpmbuild/SOURCES
rm -rfv /run/log/journal
rm -rfv /run/udev
rm -rfv /usr/bin/aspell
rm -rfv /usr/bin/brotli
rm -rfv /usr/bin/gawk
rm -rfv /usr/bin/gcm-picker
rm -rfv /usr/bin/gnome-control-center
rm -rfv /usr/bin/gnome-keyring-daemon
rm -rfv /usr/bin/gnome-logs
rm -rfv /usr/bin/gpg
rm -rfv /usr/bin/gpgv
rm -rfv /usr/bin/grep
rm -rfv /usr/bin/hcidump
rm -rfv /usr/bin/l2test
rm -rfv /usr/bin/mwm
rm -rfv /usr/bin/nautilus
rm -rfv /usr/bin/nmcli
rm -rfv /usr/bin/nm-connection-editor
rm -rfv /usr/bin/python3.6
rm -rfv /usr/bin/vi
rm -rfv /usr/include
rm -rfv /usr/lib/girepository-1.0
rm -rfv /usr/lib/gnome-shell
rm -rfv /usr/lib/gpg
rm -rfv /usr/lib/locale
rm -rfv /usr/lib/modules/
rm -rfv /usr/lib/python3.6/site-packages
rm -rfv /usr/lib/qt5/bin
rm -rfv /usr/lib/udev/hwdb.d/
rm -rfv /usr/lib64/aspell-0.60
rm -rfv /usr/lib64/cmake
rm -rfv /usr/lib64/evolution-data-server
rm -rfv /usr/lib64/firefox
rm -rfv /usr/lib64/gconv
rm -rfv /usr/lib64/gio
rm -rfv /usr/lib64/girepository-1.0
rm -rfv /usr/lib64/gnome-keyring
rm -rfv /usr/lib64/gnome-shell
rm -rfv /usr/lib64/libbluetooth.so.3.19.4
rm -rfv /usr/lib64/libbrotlienc.so.1.0.6
rm -rfv /usr/lib64/libdb.so.2.3.0
rm -rfv /usr/lib64/libdw-0.185.so
rm -rfv /usr/lib64/libedataserver-1.2.so.23.0.0
rm -rfv /usr/lib64/libfdisk.so.1.1.0
rm -rfv /usr/lib64/libgdk-x11-2.0.so.0.2400.32
rm -rfv /usr/lib64/libgnome-desktop-3.so.17.0.6
rm -rfv /usr/lib64/libldb.so.2.3.0
rm -rfv /usr/lib64/libLLVM-12.so
rm -rfv /usr/lib64/libnss_resolve.so.2
rm -rfv /usr/lib64/libpoppler.so.104.0.0
rm -rfv /usr/lib64/libQt5Designer.so.5.15.2
rm -rfv /usr/lib64/libsamba-util.so.0.0.1
rm -rfv /usr/lib64/libsamba-util.so.1.0.28
rm -rfv /usr/lib64/libsolv.so.1
rm -rfv /usr/lib64/mutter-4
rm -rfv /usr/lib64/python3.6
rm -rfv /usr/lib64/qt5/bin
rm -rfv /usr/lib64/qt5/plugins/bearer
rm -rfv /usr/lib64/qt5/plugins/geoservices
rm -rfv /usr/lib64/qt5/qml
rm -rfv /usr/lib64/rsyslog
rm -rfv /usr/lib64/samba
rm -rfv /usr/libexec/gnome-session-binary
rm -rfv /usr/libexec/nm-iface-helper
rm -rfv /usr/libexec/nm-initrd-generator
rm -rfv /usr/sbin/gdm
rm -rfv /usr/sbin/ldconfig
rm -rfv /usr/share/anaconda
rm -rfv /usr/share/applications
rm -rfv /usr/share/backgrounds
rm -rfv /usr/share/doc
rm -rfv /usr/share/gcc-8
rm -rfv /usr/share/glib-2.0
rm -rfv /usr/share/gnome
rm -rfv /usr/share/gnome-control/center
rm -rfv /usr/share/gnome-control-center
rm -rfv /usr/share/gnome-session
rm -rfv /usr/share/gnome-shell
rm -rfv /usr/share/gnupg
rm -rfv /usr/share/help/*
rm -rfv /usr/share/hwdata/
rm -rfv /usr/share/ibus/*
rm -rfv /usr/share/icons
rm -rfv /usr/share/info
rm -rfv /usr/share/libthai
rm -rfv /usr/share/licenses/libjpeg-turbo/
rm -rfv /usr/share/locale/*
rm -rfv /usr/share/man
rm -rfv /usr/share/mime/text
rm -rfv /usr/share/misc
rm -rfv /usr/share/myspell
rm -rfv /usr/share/otter-browser/locale
rm -rfv /usr/share/plymouth
rm -rfv /usr/share/polkit-1
rm -rfv /usr/share/poppler
rm -rfv /usr/share/qt5/qtwebengine_dictionaries/
rm -rfv /usr/share/qt5/translations
rm -rfv /usr/share/themes/Adwaita
rm -rfv /usr/share/vim
rm -rfv /usr/share/X11/locale
rm -rfv /usr/share/xfce4/helpers
rm -rfv /usr/share/xpdf/chinese/simplified
rm -rfv /usr/share/xpdf/chinese
rm -rfv /usr/share/xpdf/japanese
rm -rfv /usr/sher/myspell
rm -rfv /var/adm
rm -rfv /var/cache/*
rm -rfv /var/ftp
rm -rfv /var/games
rm -rfv /var/gopher
rm -rfv /var/ib/gdm
rm -rfv /var/lib/bluetooth
rm -rfv /var/lib/flatpak
rm -rfv /var/lib/gdm
rm -rfv /var/lib/rpm
rm -rfv /var/local
rm -rfv /var/lock
rm -rfv /var/log/anaconda
rm -rfv /var/log/messages
rm -rfv /var/log/sssd
rm -rfv /var/mail
rm -rfv /var/nis
rm -rfv /var/opt
rm -rfv /var/preserve
rm -rfv /var/spool
rm -rfv /var/tp
rm -rfv /var/yp
rm -rfv /var/zp
du / | sort -n
